
// export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL';

export const TOGGLE_COMPLETE_START = 'TOGGLE_COMPLETE_START';
export const TOGGLE_COMPLETE_SUCCESS = 'TOGGLE_COMPLETE_SUCCESS';
export const TOGGLE_COMPLETE_FAIL = 'TOGGLE_COMPLETE_FAIL';

export const REFRESH_TASKS_START = 'REFRESH_TASKS_START';
export const REFRESH_TASKS_SUCCESS = 'REFRESH_TASKS_SUCCESS';
export const REFRESH_TASKS_FAIL = 'REFRESH_TASKS_FAIL';

export const SAVE_NEW_TASK_START = 'SAVE_NEW_TASK_START';
export const SAVE_NEW_TASK_SUCCESS = 'SAVE_NEW_TASK_SUCCESS';
export const SAVE_NEW_TASK_FAIL = 'SAVE_NEW_TASK_FAIL';

export const SET_REDIRECT_FROM_NEW_TASK_SCREEN = 'SET_REDIRECT_FROM_NEW_TASK_SCREEN';