
// export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL';

export const TOGGLE_COMPLETE_START = 'TOGGLE_COMPLETE_START';
export const TOGGLE_COMPLETE_SUCCESS = 'TOGGLE_COMPLETE_SUCCESS';
export const TOGGLE_COMPLETE_FAIL = 'TOGGLE_COMPLETE_FAIL';

export const REFRESH_TASKS_START = 'REFRESH_TASKS_START';
export const REFRESH_TASKS_SUCCESS = 'REFRESH_TASKS_SUCCESS';
export const REFRESH_TASKS_FAIL = 'REFRESH_TASKS_FAIL';